codecov:
  token: dea04c58-c621-49a8-ac1e-5b77699805c9

coverage:
  precision: 2
  round: down
  range: "90...100"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
